image: alpine/edge
packages:
  - go
sources:
  - https://github.com/go-ap/storage-boltdb
environment:
  GO111MODULE: 'on'
tasks:
  - tests: |
      cd storage-boltdb && make test
  - conformance-suite: |
      cd storage-boltdb
      go test -tags conformance -count=1 -json . | go run github.com/gotesttools/gotestfmt/v2/cmd/gotestfmt -showteststatus
  - coverage: |
      set -a +x
      cd storage-boltdb && make coverage
