image: alpine/edge
packages:
  - go
  - golangci-lint
sources:
  - https://github.com/go-ap/storage-boltdb
secrets:
  - 0824018e-4126-4f9c-ba18-8e3933ab9c6c
environment:
  GO111MODULE: 'on'
tasks:
  - fmt: |
      cd storage-boltdb
      test -z $(gofmt -l .)
  - tests: |
      cd storage-boltdb
      make test
  - coverage: |
      cd storage-boltdb
      git switch -C master origin/master
      make coverage
      go tool goveralls -flagname unit-tests -service=${CI_NAME} -coverprofile storage-boltdb.coverprofile -repotokenfile ~/.coveralls.tok
  - lint: |
      cd storage-boltdb
      golangci-lint run || true
