image: alpine/edge
packages:
  - go
sources:
  - https://github.com/go-ap/storage-boltdb
secrets:
  - 0824018e-4126-4f9c-ba18-8e3933ab9c6c
environment:
  GO111MODULE: 'on'
tasks:
  - tests: |
      cd storage-boltdb
      make test
  - coverage: |
      cd storage-boltdb
      git switch -C master origin/master
      make coverage
      go run github.com/mattn/goveralls@latest -flagname unit-tests -service=${CI_NAME} -coverprofile storage-boltdb.coverprofile -repotokenfile ~/.coveralls.tok
